# Generated by Django 6.0.6 on 2026-07-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Current consecutive days of practice'),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Date of last completed assessment', null=True),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0, help_text='Longest streak achieved'),
        ),
    ]
