# Generated by Django 6.0.6 on 2026-07-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0002_individualuser_current_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_granted', models.BooleanField(default=False, help_text='User consented to share results with institution')),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_individuals', to='UserAPI.businessuser')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to='UserAPI.individualuser')),
            ],
            options={
                'unique_together': {('individual', 'business')},
            },
        ),
    ]
