# Generated by Django 6.0.6 on 2026-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0003_institutionmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='media_retention_days',
            field=models.PositiveIntegerField(choices=[(15, '15 days'), (30, '30 days'), (60, '60 days')], default=30, help_text='How long to keep interview recordings before automatic deletion'),
        ),
    ]
