# Generated by Django 6.0.6 on 2026-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0004_individualuser_media_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='video_consent_given_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user consented to video recording and analysis', null=True),
        ),
    ]
