# Generated by Django 6.0.6 on 2026-07-31 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0005_individualuser_video_consent_given_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterviewerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.CharField(default='friendly_encouraging', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
