# Generated by Django 6.0.6 on 2026-08-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0006_userinterviewerpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('enterprise', 'Enterprise')], default='monthly', max_length=20)),
                ('seat_limit', models.IntegerField(blank=True, help_text='Max linked students. NULL = unlimited.', null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('institution_member', 'Institution Member')], default='free', max_length=20)),
                ('premium_expires_at', models.DateTimeField(blank=True, help_text='When premium expires. NULL = free tier or lifetime premium.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_subscriptions', to='UserAPI.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
            },
        ),
    ]
