# Generated by Django 6.0.6 on 2026-08-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0008_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('institution_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_interest', models.CharField(choices=[('institution', 'Institution'), ('institution_annual', 'Institution Annual'), ('enterprise', 'Enterprise')], max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Sales Inquiry',
                'verbose_name_plural': 'Sales Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
