# Generated by Django 6.0.6 on 2026-08-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0009_salesinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='seat_limit',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='subscription_expires_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='UserAPI.institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='max_seats',
            field=models.IntegerField(blank=True, help_text='Blank means unlimited', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='sales_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAPI.salesinquiry'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Enterprise', 'Enterprise')], max_length=20),
        ),
    ]
