# Generated by Django 6.0.6 on 2026-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0010_remove_institution_seat_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='face_reference_captured_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when reference photo was captured', null=True),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='face_reference_photo',
            field=models.ImageField(blank=True, help_text='Reference photo for face verification during assessments', null=True, upload_to='face_references/'),
        ),
    ]
