from django.db import models
from django.contrib.auth import get_user_model
from UserAPI.models import BusinessUser
import uuid
import random
import string

User = get_user_model()

class PlatformJobTitle(models.Model):
    """Platform-maintained job titles available for individual assessments"""
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    category = models.CharField(max_length=100, choices=[
        ('technology', 'Technology'),
        ('finance', 'Finance'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
        ('operations', 'Operations'),
        ('hr', 'Human Resources'),
        ('consulting', 'Consulting'),
        ('healthcare', 'Healthcare'),
        ('education', 'Education'),
        ('engineering', 'Engineering'),
        ('analytics', 'Analytics'),
        ('management', 'Management'),
        ('other', 'Other'),
    ], default='other')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['category', 'title']
    
    def __str__(self):
        return f"{self.title} ({self.category})"

class PlatformQuestion(models.Model):
    """Platform-maintained questions for job titles"""
    QUESTION_TYPES = [
        ('behavioral', 'Behavioral'),
        ('technical', 'Technical'),
        ('situational', 'Situational'),
        ('general', 'General'),
    ]
    
    job_title = models.ForeignKey(PlatformJobTitle, on_delete=models.CASCADE, related_name='questions')
    question_text = models.TextField()
    ideal_answer_points = models.TextField(blank=True, null=True, help_text="Optional key points a strong answer should cover")
    question_type = models.CharField(max_length=50, choices=QUESTION_TYPES, default='general')
    is_mandatory = models.BooleanField(default=False, help_text="Mandatory questions are always asked")
    difficulty_level = models.CharField(max_length=20, choices=[
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ], default='intermediate')
    expected_duration = models.PositiveIntegerField(default=120, help_text="Expected answer duration in seconds")
    order = models.PositiveIntegerField(default=1)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['order', 'created_at']
    
    def __str__(self):
        return f"{self.job_title.title} - Q{self.order}"

class JobRole(models.Model):
    """Job roles maintained by business users"""
    business_user = models.ForeignKey(BusinessUser, on_delete=models.CASCADE, related_name='job_roles')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ['business_user', 'title']
    
    def __str__(self):
        return f"{self.title} - {self.business_user.company_name or self.business_user.name}"

class InterviewQuestion(models.Model):
    """Questions for specific job roles"""
    job_role = models.ForeignKey(JobRole, on_delete=models.CASCADE, related_name='questions')
    question_text = models.TextField()
    ideal_answer_points = models.TextField(blank=True, null=True, help_text="Optional key points a strong answer should cover")
    question_type = models.CharField(max_length=50, choices=[
        ('behavioral', 'Behavioral'),
        ('technical', 'Technical'),
        ('situational', 'Situational'),
        ('general', 'General'),
    ], default='general')
    difficulty_level = models.CharField(max_length=20, choices=[
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ], default='intermediate', help_text="Difficulty tier for adaptive selection")
    order = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['order', 'created_at']
    
    def __str__(self):
        return f"{self.job_role.title} - Q{self.order}"

class AssessmentLink(models.Model):
    """Links generated by business users for candidates"""
    job_role = models.ForeignKey(JobRole, on_delete=models.CASCADE, related_name='assessment_links')
    unique_link = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    access_code = models.CharField(max_length=8, unique=True)
    is_active = models.BooleanField(default=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        if not self.access_code:
            self.access_code = self.generate_access_code()
        super().save(*args, **kwargs)
    
    def generate_access_code(self):
        """Generate a unique 8-character access code"""
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
            if not AssessmentLink.objects.filter(access_code=code).exists():
                return code
    
    def __str__(self):
        return f"{self.job_role.title} - {self.access_code}"

class Assessment(models.Model):
    """Individual assessments taken by candidates"""
    ASSESSMENT_TYPE_CHOICES = [
        ('individual', 'Individual Practice'),
        ('business', 'Business Assessment'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('expired', 'Expired'),
    ]
    
    # For individual assessments
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='assessments')
    
    # For business assessments
    assessment_link = models.ForeignKey(AssessmentLink, on_delete=models.CASCADE, null=True, blank=True)
    candidate_name = models.CharField(max_length=100, blank=True)
    candidate_email = models.EmailField(blank=True)
    
    # Common fields
    assessment_type = models.CharField(max_length=20, choices=ASSESSMENT_TYPE_CHOICES)
    job_title = models.CharField(max_length=200)  # For individual assessments or copied from job_role
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    
    # Assessment data
    video_file = models.FileField(upload_to='assessments/videos/', null=True, blank=True)
    recording_duration = models.PositiveIntegerField(null=True, blank=True)  # in seconds
    
    # Timestamps
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # Adaptive Interview Engine fields
    adaptive_mode = models.BooleanField(default=True, help_text="Whether adaptive difficulty adjustment is enabled. Always ON for Business Assessment.")
    adaptive_path = models.JSONField(default=list, blank=True, help_text="List of adaptive decisions: [{question_order, previous_difficulty, performance_score, next_difficulty, reason}]")
    current_difficulty = models.CharField(max_length=20, choices=[
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ], default='intermediate', help_text="Current difficulty tier for adaptive selection")
    
    def __str__(self):
        if self.assessment_type == 'individual':
            return f"{self.user.username} - {self.job_title}"
        else:
            return f"{self.candidate_name or 'Anonymous'} - {self.job_title}"

class AssessmentResult(models.Model):
    """Results and analysis of completed assessments"""
    assessment = models.OneToOneField(Assessment, on_delete=models.CASCADE, related_name='result')
    
    # Body language analysis
    posture_score = models.FloatField(null=True, blank=True)
    eye_contact_score = models.FloatField(null=True, blank=True)
    gesture_score = models.FloatField(null=True, blank=True)
    
    # Attire analysis
    attire_appropriateness = models.CharField(max_length=20, choices=[
        ('excellent', 'Excellent'),
        ('good', 'Good'),
        ('fair', 'Fair'),
        ('poor', 'Poor'),
    ], null=True, blank=True)
    attire_feedback = models.TextField(blank=True)
    
    # Speech analysis
    speech_clarity = models.FloatField(null=True, blank=True)
    speech_pace = models.FloatField(null=True, blank=True)
    confidence_score = models.FloatField(null=True, blank=True)
    
    # Overall
    overall_score = models.FloatField(null=True, blank=True)
    feedback = models.TextField(blank=True)
    recommendations = models.TextField(blank=True)
    
    # Analysis metadata
    analyzed_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Result for {self.assessment}"


class CompanyProfile(models.Model):
    """Company profiles for tailored interview experiences"""
    name = models.CharField(max_length=200, unique=True)
    industry = models.CharField(max_length=100)
    interview_style_notes = models.TextField(
        help_text="Description of the company's interview culture and style used to guide AI question generation."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name

class IndividualAssessment(models.Model):
    """Individual practice assessments using platform job titles"""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('terminated', 'Terminated'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='individual_assessments')
    platform_job_title = models.ForeignKey(PlatformJobTitle, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    session_id = models.UUIDField(default=uuid.uuid4, unique=True)
    
    # Institution linkage (optional)
    institution_membership = models.ForeignKey(
        'UserAPI.InstitutionMembership', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='assessments'
    )
    
    @classmethod
    def get_platform_average_for_job(cls, job_title_id, min_assessments=5):
        """Get average score for a specific job title across all users"""
        assessments = cls.objects.filter(
            platform_job_title_id=job_title_id,
            status='completed',
            overall_score__isnull=False
        )
        
        if assessments.count() < min_assessments:
            return None
        
        avg_score = assessments.aggregate(avg_score=models.Avg('overall_score'))['avg_score']
        return round(avg_score, 1) if avg_score else None
    
    # Assessment configuration
    total_questions = models.PositiveIntegerField(default=0)
    current_question_index = models.PositiveIntegerField(default=0)
    selected_questions = models.JSONField(default=list, help_text="List of question IDs for this assessment")
    
    # Timing
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    estimated_duration = models.PositiveIntegerField(default=1800, help_text="Estimated duration in seconds")
    
    # Security and monitoring
    fullscreen_violations = models.PositiveIntegerField(default=0)
    warnings_given = models.PositiveIntegerField(default=0)
    browser_focus_lost = models.PositiveIntegerField(default=0)
    
    # Analysis scores (filled after completion)
    overall_score = models.FloatField(null=True, blank=True)
    body_language_score = models.FloatField(null=True, blank=True)
    attire_score = models.FloatField(null=True, blank=True)
    speaking_score = models.FloatField(null=True, blank=True)
    relevance_score = models.FloatField(null=True, blank=True)
    voice_confidence_score = models.FloatField(null=True, blank=True)

    # Improvement roadmap — structured JSON generated by Groq after scoring
    improvement_roadmap = models.JSONField(null=True, blank=True, help_text="Structured improvement roadmap JSON from generate_improvement_roadmap()")

    # Skill Gap Detection — one-shot post-completion analysis of competency gaps vs strengths
    skill_gap_analysis = models.JSONField(
        null=True,
        blank=True,
        help_text="Structured skill gaps/strengths JSON from generate_skill_gap_analysis()",
    )

    # Personalized Learning Roadmap — multi-week curriculum based on skill gaps
    learning_roadmap = models.JSONField(
        null=True, 
        blank=True, 
        help_text="Structured multi-week learning path from generate_learning_roadmap()"
    )

    # AI Personality & Communication Analysis — whole-assessment style analysis
    communication_analysis = models.JSONField(
        null=True,
        blank=True,
        help_text=(
            "Communication style analysis from generate_communication_analysis(). "
            "Schema: {summary: str, traits: [{label: str, explanation: str}, ...]}"
        ),
    )

    # AI Interview Coach data — comprehensive coaching insights
    ai_coach_summary = models.TextField(blank=True, null=True, help_text="Overall summary of performance")
    ai_coach_strengths = models.JSONField(null=True, blank=True, help_text="List of strengths identified")
    ai_coach_weaknesses = models.JSONField(null=True, blank=True, help_text="List of weaknesses identified")
    ai_coach_action_plan = models.JSONField(null=True, blank=True, help_text="Structured action plan with timeline")
    ai_coach_recommended_topics = models.JSONField(null=True, blank=True, help_text="List of recommended practice topics")
    ai_coach_generated_at = models.DateTimeField(null=True, blank=True, help_text="When AI coaching was generated")
    ai_coach_status = models.CharField(max_length=20, default='pending', choices=[
        ('pending', 'Pending'),
        ('generated', 'Generated'),
        ('failed', 'Failed'),
    ], help_text="Status of AI coaching generation")

    # Adaptive Interview Engine fields
    adaptive_mode = models.BooleanField(default=True, help_text="Whether adaptive difficulty adjustment is enabled")
    adaptive_path = models.JSONField(default=list, blank=True, help_text="List of adaptive decisions: [{question_order, previous_difficulty, performance_score, next_difficulty, reason}]")
    current_difficulty = models.CharField(max_length=20, choices=[
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ], default='intermediate', help_text="Current difficulty tier for adaptive selection")

    # Follow-up Engine fields
    pending_follow_up_text = models.TextField(null=True, blank=True, help_text="AI-generated follow-up question waiting to be asked")
    pending_follow_up_reason = models.TextField(null=True, blank=True, help_text="Reason for generating the follow-up")
    session_follow_up_count = models.PositiveIntegerField(default=0, help_text="Number of follow-ups asked in this session")

    # Interview Mode field
    interview_mode = models.CharField(
        max_length=20,
        choices=[
            ('hr', 'HR'),
            ('technical', 'Technical'),
            ('managerial', 'Managerial'),
            ('stress', 'Stress'),
            ('rapid_fire', 'Rapid Fire'),
        ],
        default='hr',
        help_text='Interview style/mode for this assessment'
    )
    
    # Target Company field
    target_company = models.ForeignKey(
        CompanyProfile, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        help_text="Optional target company selected for tailored questions"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.user.email} - {self.platform_job_title.title} ({self.status})"
    
    def get_next_question(self):
        """Get the next question for this assessment"""
        if self.current_question_index < len(self.selected_questions):
            question_id = self.selected_questions[self.current_question_index]
            return PlatformQuestion.objects.get(id=question_id)
        return None
    
    def select_questions_adaptive(self, num_non_mandatory=5):
        """Select questions for adaptive assessment based on current difficulty.

        For adaptive mode, we select mandatory questions plus placeholders or 
        initially select questions of the default difficulty. These will be 
        swapped out dynamically after each answer in views.py.
        """
        if self.selected_questions:
            return  # Already selected

        # Always include mandatory questions regardless of difficulty
        mandatory_questions = list(
            self.platform_job_title.questions.filter(is_mandatory=True, is_active=True)
            .order_by('?')
            .values_list('id', flat=True)
        )

        # Select initial non-mandatory questions from current difficulty tier
        available_questions = self.platform_job_title.questions.filter(
            is_mandatory=False,
            is_active=True,
            difficulty_level=self.current_difficulty
        )

        # If not enough questions at current difficulty, supplement from other tiers
        needed = num_non_mandatory
        selected_by_difficulty = list(
            available_questions.order_by('?')[:needed]
            .values_list('id', flat=True)
        )

        if len(selected_by_difficulty) < needed:
            # Supplement from other difficulty tiers (prefer intermediate)
            remaining_needed = needed - len(selected_by_difficulty)
            other_questions = self.platform_job_title.questions.filter(
                is_mandatory=False,
                is_active=True
            ).exclude(id__in=selected_by_difficulty + mandatory_questions)
            
            # Prefer intermediate questions as fallback
            fallback_questions = list(
                other_questions.filter(difficulty_level='intermediate')
                .order_by('?')[:remaining_needed]
                .values_list('id', flat=True)
            )
            
            if len(fallback_questions) < remaining_needed:
                # Still need more, take from any difficulty
                remaining_needed = remaining_needed - len(fallback_questions)
                any_questions = list(
                    other_questions.exclude(id__in=fallback_questions)
                    .order_by('?')[:remaining_needed]
                    .values_list('id', flat=True)
                )
                selected_by_difficulty.extend(fallback_questions + any_questions)
            else:
                selected_by_difficulty.extend(fallback_questions)

        all_selected = mandatory_questions + selected_by_difficulty
        random.shuffle(all_selected)  # Randomize the final question order

        self.selected_questions = all_selected
        self.total_questions = len(all_selected)
        self.save()
        
    def adjust_upcoming_questions_for_difficulty(self):
        """
        Re-selects the remaining unasked, non-mandatory questions in `self.selected_questions`
        to match `self.current_difficulty`.
        """
        if not self.adaptive_mode:
            return
            
        current_index = self.current_question_index
        if current_index >= len(self.selected_questions):
            return
            
        upcoming_ids = self.selected_questions[current_index:]
        asked_ids = self.selected_questions[:current_index]
        
        upcoming_qs = list(PlatformQuestion.objects.filter(id__in=upcoming_ids))
        
        new_upcoming_ids = []
        for q_id in upcoming_ids:
            q = next((x for x in upcoming_qs if x.id == q_id), None)
            if not q:
                continue
                
            if q.is_mandatory:
                new_upcoming_ids.append(q_id)
            else:
                excluded_ids = asked_ids + new_upcoming_ids
                new_q = self.platform_job_title.questions.filter(
                    is_mandatory=False,
                    is_active=True,
                    difficulty_level=self.current_difficulty
                ).exclude(id__in=excluded_ids).order_by('?').first()
                
                if new_q:
                    new_upcoming_ids.append(new_q.id)
                else:
                    fallback_q = self.platform_job_title.questions.filter(
                        is_mandatory=False,
                        is_active=True
                    ).exclude(id__in=excluded_ids).order_by('?').first()
                    if fallback_q:
                        new_upcoming_ids.append(fallback_q.id)
                    else:
                        new_upcoming_ids.append(q_id)
                        
        self.selected_questions = asked_ids + new_upcoming_ids
        self.save()
    
    def select_questions(self, num_non_mandatory=5):
        """Select questions for this assessment (mandatory + random non-mandatory).

        Uses Django's `order_by('?')` random ordering so a fresh, differently
        ordered set of questions is drawn from the PlatformQuestion bank every
        time an assessment is started, even for the same job role.

        If adaptive_mode is True, uses select_questions_adaptive() instead.
        """
        if self.selected_questions:
            return  # Already selected

        if self.adaptive_mode:
            self.select_questions_adaptive(num_non_mandatory)
            return

        # Non-adaptive mode: original random selection
        mandatory_questions = list(
            self.platform_job_title.questions.filter(is_mandatory=True, is_active=True)
            .order_by('?')
            .values_list('id', flat=True)
        )

        non_mandatory_questions = list(
            self.platform_job_title.questions.filter(is_mandatory=False, is_active=True)
            .order_by('?')[:num_non_mandatory]
            .values_list('id', flat=True)
        )

        all_selected = mandatory_questions + non_mandatory_questions
        random.shuffle(all_selected)  # Randomize the final question order too

        self.selected_questions = all_selected
        self.total_questions = len(all_selected)
        self.save()


class IndividualAssessmentResponse(models.Model):
    """Individual responses to assessment questions"""
    assessment = models.ForeignKey(IndividualAssessment, on_delete=models.CASCADE, related_name='responses')
    question = models.ForeignKey(PlatformQuestion, on_delete=models.CASCADE)
    question_order = models.PositiveIntegerField()
    
    # Response data
    audio_file = models.FileField(upload_to='assessments/audio/', null=True, blank=True)
    video_file = models.FileField(upload_to='assessments/video/', null=True, blank=True)
    response_text = models.TextField(blank=True, help_text="Transcribed text from audio")
    
    # Timing
    question_started_at = models.DateTimeField()
    response_started_at = models.DateTimeField(null=True, blank=True)
    response_ended_at = models.DateTimeField(null=True, blank=True)
    response_duration = models.PositiveIntegerField(null=True, blank=True, help_text="Duration in seconds")
    time_to_start = models.PositiveIntegerField(null=True, blank=True, help_text="Time taken to start speaking in seconds")
    
    # Analysis results
    fluency_score = models.FloatField(null=True, blank=True)
    pronunciation_score = models.FloatField(null=True, blank=True)
    formality_score = models.FloatField(null=True, blank=True)
    relevance_score = models.FloatField(null=True, blank=True)
    confidence_score = models.FloatField(null=True, blank=True)
    
    # Detailed analysis
    analysis_data = models.JSONField(default=dict, help_text="Detailed analysis results")

    # STAR Framework Analysis — per-response, behavioral questions only
    star_analysis = models.JSONField(
        null=True,
        blank=True,
        help_text=(
            "STAR structure analysis for behavioral responses. "
            "Schema: {situation: bool, task: bool, action: bool, result: bool, "
            "score: float 0-10, missing_explanation: str}"
        ),
    )

    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.assessment.user.email} - Q{self.question_order}"


class FollowUpResponse(models.Model):
    """Follow-up responses generated for an assessment response"""
    parent_response = models.ForeignKey(IndividualAssessmentResponse, on_delete=models.CASCADE, related_name='follow_ups')
    follow_up_prompt = models.TextField(help_text="The AI-generated follow-up question text")
    follow_up_reason = models.TextField(null=True, blank=True, help_text="Why this follow-up was triggered")
    answer_text = models.TextField(null=True, blank=True)
    audio_file = models.FileField(upload_to='assessments/follow_up_audio/', null=True, blank=True)
    video_file = models.FileField(upload_to='assessments/follow_up_video/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class AssessmentSnapshot(models.Model):
    """Snapshots taken during assessment for body language and attire analysis"""
    ANALYSIS_TYPES = [
        ('body_language', 'Body Language'),
        ('attire', 'Attire'),
    ]
    
    assessment = models.ForeignKey(IndividualAssessment, on_delete=models.CASCADE, related_name='snapshots')
    analysis_type = models.CharField(max_length=20, choices=ANALYSIS_TYPES)
    image_file = models.FileField(upload_to='assessments/snapshots/')
    timestamp = models.DateTimeField()
    
    # Analysis results
    score = models.FloatField(null=True, blank=True)
    analysis_data = models.JSONField(default=dict)
    feedback = models.TextField(blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.assessment.user.email} - {self.analysis_type} at {self.timestamp}"


class BusinessAssessmentResponse(models.Model):
    """Individual responses for business assessments (one per question)"""
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE, related_name='responses')
    question_order = models.PositiveIntegerField()
    question_text = models.TextField()
    
    # Response data
    audio_file = models.FileField(upload_to='assessments/business/audio/', null=True, blank=True)
    response_duration = models.PositiveIntegerField(null=True, blank=True, help_text="Duration in seconds")
    
    # Analysis results
    analysis_data = models.JSONField(default=dict)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ['assessment', 'question_order']
        ordering = ['question_order']
    
    def __str__(self):
        return f"{self.assessment} - Q{self.question_order}"


class BusinessAssessmentSnapshot(models.Model):
    """Snapshots for business assessments"""  
    ANALYSIS_TYPES = [
        ('body_language', 'Body Language'),
        ('attire', 'Attire'),
    ]
    
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE, related_name='snapshots')
    analysis_type = models.CharField(max_length=20, choices=ANALYSIS_TYPES)
    timestamp = models.DateTimeField()
    
    # Analysis results
    score = models.FloatField(null=True, blank=True)
    analysis_data = models.JSONField(default=dict)
    feedback = models.TextField(blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.assessment} - {self.analysis_type} at {self.timestamp}"


class ResumeReview(models.Model):
    resume_file = models.FileField(upload_to='resumes/')
    overall_score = models.FloatField()
    feedback = models.JSONField()
    ats_score = models.FloatField(null=True, blank=True)
    ats_feedback = models.JSONField(default=dict, blank=True)
    version_number = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('UserAPI.CustomUser', on_delete=models.CASCADE, related_name='resume_reviews')

    class Meta:
        db_table = 'AnalysisAPI_resumereview'

    def __str__(self):
        return f"Resume Review for {self.user.email} at {self.created_at}"


class CoverLetter(models.Model):
    """AI-generated cover letters — standalone feature separate from ResumeReview."""
    user = models.ForeignKey(
        'UserAPI.CustomUser',
        on_delete=models.CASCADE,
        related_name='cover_letters',
    )
    job_title = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255, blank=True)
    job_description = models.TextField(blank=True)
    resume_review = models.ForeignKey(
        'ResumeReview',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='cover_letters',
    )
    generated_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Cover Letter for {self.job_title} - {self.user.email}"


class LinkedInPost(models.Model):
    """AI-generated LinkedIn posts — standalone feature."""
    user = models.ForeignKey(
        'UserAPI.CustomUser',
        on_delete=models.CASCADE,
        related_name='linkedin_posts'
    )
    topic = models.CharField(max_length=255)
    tone = models.CharField(max_length=50, default='professional')
    resume_review = models.ForeignKey(
        'ResumeReview',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='linkedin_posts'
    )
    generated_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"LinkedIn Post: {self.topic} - {self.user.email}"


class InterviewSummaryVideo(models.Model):
    assessment = models.ForeignKey('IndividualAssessment', on_delete=models.CASCADE,
                                    related_name='summary_videos')
    user = models.ForeignKey('UserAPI.CustomUser', on_delete=models.CASCADE,
                              related_name='summary_videos')
    video_file = models.FileField(upload_to='summary_videos/', null=True, blank=True)
    status = models.CharField(max_length=20, default='pending')
    error_message = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Summary Video for {self.assessment.session_id} - {self.status}"
