from django.db import models
from django.contrib.auth import get_user_model
from UserAPI.models import BusinessUser
import uuid
import random
import string

User = get_user_model()

class PlatformJobTitle(models.Model):
    """Platform-maintained job titles available for individual assessments"""
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    category = models.CharField(max_length=100, choices=[
        ('technology', 'Technology'),
        ('finance', 'Finance'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
        ('operations', 'Operations'),
        ('hr', 'Human Resources'),
        ('consulting', 'Consulting'),
        ('healthcare', 'Healthcare'),
        ('education', 'Education'),
        ('engineering', 'Engineering'),
        ('other', 'Other'),
    ], default='other')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['category', 'title']
    
    def __str__(self):
        return f"{self.title} ({self.category})"

class PlatformQuestion(models.Model):
    """Platform-maintained questions for job titles"""
    QUESTION_TYPES = [
        ('behavioral', 'Behavioral'),
        ('technical', 'Technical'),
        ('situational', 'Situational'),
        ('general', 'General'),
    ]
    
    job_title = models.ForeignKey(PlatformJobTitle, on_delete=models.CASCADE, related_name='questions')
    question_text = models.TextField()
    question_type = models.CharField(max_length=50, choices=QUESTION_TYPES, default='general')
    is_mandatory = models.BooleanField(default=False, help_text="Mandatory questions are always asked")
    difficulty_level = models.CharField(max_length=20, choices=[
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ], default='intermediate')
    expected_duration = models.PositiveIntegerField(default=120, help_text="Expected answer duration in seconds")
    order = models.PositiveIntegerField(default=1)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['order', 'created_at']
    
    def __str__(self):
        return f"{self.job_title.title} - Q{self.order}"

class JobRole(models.Model):
    """Job roles maintained by business users"""
    business_user = models.ForeignKey(BusinessUser, on_delete=models.CASCADE, related_name='job_roles')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ['business_user', 'title']
    
    def __str__(self):
        return f"{self.title} - {self.business_user.company_name or self.business_user.name}"

class InterviewQuestion(models.Model):
    """Questions for specific job roles"""
    job_role = models.ForeignKey(JobRole, on_delete=models.CASCADE, related_name='questions')
    question_text = models.TextField()
    question_type = models.CharField(max_length=50, choices=[
        ('behavioral', 'Behavioral'),
        ('technical', 'Technical'),
        ('situational', 'Situational'),
        ('general', 'General'),
    ], default='general')
    order = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['order', 'created_at']
    
    def __str__(self):
        return f"{self.job_role.title} - Q{self.order}"

class AssessmentLink(models.Model):
    """Links generated by business users for candidates"""
    job_role = models.ForeignKey(JobRole, on_delete=models.CASCADE, related_name='assessment_links')
    unique_link = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    access_code = models.CharField(max_length=8, unique=True)
    is_active = models.BooleanField(default=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        if not self.access_code:
            self.access_code = self.generate_access_code()
        super().save(*args, **kwargs)
    
    def generate_access_code(self):
        """Generate a unique 8-character access code"""
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
            if not AssessmentLink.objects.filter(access_code=code).exists():
                return code
    
    def __str__(self):
        return f"{self.job_role.title} - {self.access_code}"

class Assessment(models.Model):
    """Individual assessments taken by candidates"""
    ASSESSMENT_TYPE_CHOICES = [
        ('individual', 'Individual Practice'),
        ('business', 'Business Assessment'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('expired', 'Expired'),
    ]
    
    # For individual assessments
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='assessments')
    
    # For business assessments
    assessment_link = models.ForeignKey(AssessmentLink, on_delete=models.CASCADE, null=True, blank=True)
    candidate_name = models.CharField(max_length=100, blank=True)
    candidate_email = models.EmailField(blank=True)
    
    # Common fields
    assessment_type = models.CharField(max_length=20, choices=ASSESSMENT_TYPE_CHOICES)
    job_title = models.CharField(max_length=200)  # For individual assessments or copied from job_role
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    
    # Assessment data
    video_file = models.FileField(upload_to='assessments/videos/', null=True, blank=True)
    recording_duration = models.PositiveIntegerField(null=True, blank=True)  # in seconds
    
    # Timestamps
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        if self.assessment_type == 'individual':
            return f"{self.user.username} - {self.job_title}"
        else:
            return f"{self.candidate_name or 'Anonymous'} - {self.job_title}"

class AssessmentResult(models.Model):
    """Results and analysis of completed assessments"""
    assessment = models.OneToOneField(Assessment, on_delete=models.CASCADE, related_name='result')
    
    # Body language analysis
    posture_score = models.FloatField(null=True, blank=True)
    eye_contact_score = models.FloatField(null=True, blank=True)
    gesture_score = models.FloatField(null=True, blank=True)
    
    # Attire analysis
    attire_appropriateness = models.CharField(max_length=20, choices=[
        ('excellent', 'Excellent'),
        ('good', 'Good'),
        ('fair', 'Fair'),
        ('poor', 'Poor'),
    ], null=True, blank=True)
    attire_feedback = models.TextField(blank=True)
    
    # Speech analysis
    speech_clarity = models.FloatField(null=True, blank=True)
    speech_pace = models.FloatField(null=True, blank=True)
    confidence_score = models.FloatField(null=True, blank=True)
    
    # Overall
    overall_score = models.FloatField(null=True, blank=True)
    feedback = models.TextField(blank=True)
    recommendations = models.TextField(blank=True)
    
    # Analysis metadata
    analyzed_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Result for {self.assessment}"


class IndividualAssessment(models.Model):
    """Individual practice assessments using platform job titles"""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('terminated', 'Terminated'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='individual_assessments')
    platform_job_title = models.ForeignKey(PlatformJobTitle, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    session_id = models.UUIDField(default=uuid.uuid4, unique=True)
    
    # Assessment configuration
    total_questions = models.PositiveIntegerField(default=0)
    current_question_index = models.PositiveIntegerField(default=0)
    selected_questions = models.JSONField(default=list, help_text="List of question IDs for this assessment")
    
    # Timing
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    estimated_duration = models.PositiveIntegerField(default=1800, help_text="Estimated duration in seconds")
    
    # Security and monitoring
    fullscreen_violations = models.PositiveIntegerField(default=0)
    warnings_given = models.PositiveIntegerField(default=0)
    browser_focus_lost = models.PositiveIntegerField(default=0)
    
    # Analysis scores (filled after completion)
    overall_score = models.FloatField(null=True, blank=True)
    body_language_score = models.FloatField(null=True, blank=True)
    attire_score = models.FloatField(null=True, blank=True)
    speaking_score = models.FloatField(null=True, blank=True)
    relevance_score = models.FloatField(null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.user.email} - {self.platform_job_title.title} ({self.status})"
    
    def get_next_question(self):
        """Get the next question for this assessment"""
        if self.current_question_index < len(self.selected_questions):
            question_id = self.selected_questions[self.current_question_index]
            return PlatformQuestion.objects.get(id=question_id)
        return None
    
    def select_questions(self):
        """Select questions for this assessment (mandatory + random non-mandatory)"""
        if self.selected_questions:
            return  # Already selected
            
        mandatory_questions = list(
            self.platform_job_title.questions.filter(is_mandatory=True, is_active=True)
            .values_list('id', flat=True)
        )
        
        non_mandatory_questions = list(
            self.platform_job_title.questions.filter(is_mandatory=False, is_active=True)
            .values_list('id', flat=True)
        )
        
        # Select up to 5 random non-mandatory questions
        random_questions = random.sample(
            non_mandatory_questions, 
            min(5, len(non_mandatory_questions))
        )
        
        all_selected = mandatory_questions + random_questions
        random.shuffle(all_selected)  # Randomize order
        
        self.selected_questions = all_selected
        self.total_questions = len(all_selected)
        self.save()


class IndividualAssessmentResponse(models.Model):
    """Individual responses to assessment questions"""
    assessment = models.ForeignKey(IndividualAssessment, on_delete=models.CASCADE, related_name='responses')
    question = models.ForeignKey(PlatformQuestion, on_delete=models.CASCADE)
    question_order = models.PositiveIntegerField()
    
    # Response data
    audio_file = models.FileField(upload_to='assessments/audio/', null=True, blank=True)
    video_file = models.FileField(upload_to='assessments/video/', null=True, blank=True)
    response_text = models.TextField(blank=True, help_text="Transcribed text from audio")
    
    # Timing
    question_started_at = models.DateTimeField()
    response_started_at = models.DateTimeField(null=True, blank=True)
    response_ended_at = models.DateTimeField(null=True, blank=True)
    response_duration = models.PositiveIntegerField(null=True, blank=True, help_text="Duration in seconds")
    time_to_start = models.PositiveIntegerField(null=True, blank=True, help_text="Time taken to start speaking in seconds")
    
    # Analysis results
    fluency_score = models.FloatField(null=True, blank=True)
    pronunciation_score = models.FloatField(null=True, blank=True)
    formality_score = models.FloatField(null=True, blank=True)
    relevance_score = models.FloatField(null=True, blank=True)
    confidence_score = models.FloatField(null=True, blank=True)
    
    # Detailed analysis
    analysis_data = models.JSONField(default=dict, help_text="Detailed analysis results")
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.assessment.user.email} - Q{self.question_order}"


class AssessmentSnapshot(models.Model):
    """Snapshots taken during assessment for body language and attire analysis"""
    ANALYSIS_TYPES = [
        ('body_language', 'Body Language'),
        ('attire', 'Attire'),
    ]
    
    assessment = models.ForeignKey(IndividualAssessment, on_delete=models.CASCADE, related_name='snapshots')
    analysis_type = models.CharField(max_length=20, choices=ANALYSIS_TYPES)
    image_file = models.FileField(upload_to='assessments/snapshots/')
    timestamp = models.DateTimeField()
    
    # Analysis results
    score = models.FloatField(null=True, blank=True)
    analysis_data = models.JSONField(default=dict)
    feedback = models.TextField(blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.assessment.user.email} - {self.analysis_type} at {self.timestamp}"


class BusinessAssessmentResponse(models.Model):
    """Individual responses for business assessments (one per question)"""
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE, related_name='responses')
    question_order = models.PositiveIntegerField()
    question_text = models.TextField()
    
    # Response data
    audio_file = models.FileField(upload_to='assessments/business/audio/', null=True, blank=True)
    response_duration = models.PositiveIntegerField(null=True, blank=True, help_text="Duration in seconds")
    
    # Analysis results
    analysis_data = models.JSONField(default=dict)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ['assessment', 'question_order']
        ordering = ['question_order']
    
    def __str__(self):
        return f"{self.assessment} - Q{self.question_order}"


class BusinessAssessmentSnapshot(models.Model):
    """Snapshots for business assessments"""  
    ANALYSIS_TYPES = [
        ('body_language', 'Body Language'),
        ('attire', 'Attire'),
    ]
    
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE, related_name='snapshots')
    analysis_type = models.CharField(max_length=20, choices=ANALYSIS_TYPES)
    timestamp = models.DateTimeField()
    
    # Analysis results
    score = models.FloatField(null=True, blank=True)
    analysis_data = models.JSONField(default=dict)
    feedback = models.TextField(blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.assessment} - {self.analysis_type} at {self.timestamp}"
