"""
Django settings for PersonaBackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from decouple import Csv, config
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add AnalysisModules to Python path so AnalysisAPI can be found
sys.path.insert(0, str(BASE_DIR / 'AnalysisModules'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Load from .env in project root (see python-decouple). .env is gitignored.
# Keep a stable secret key between app restarts so existing sessions do not get invalidated.
SECRET_KEY_FILE = BASE_DIR / '.secret_key'
if os.environ.get('SECRET_KEY'):
    SECRET_KEY = os.environ['SECRET_KEY']
elif SECRET_KEY_FILE.exists():
    SECRET_KEY = SECRET_KEY_FILE.read_text(encoding='utf-8').strip()
else:
    SECRET_KEY = get_random_secret_key()
    SECRET_KEY_FILE.write_text(SECRET_KEY, encoding='utf-8')
GROQ_API_KEY = config('GROQ_API_KEY', default=None)
GROQ_MODEL = config('GROQ_MODEL', default='llama-3.3-70b-versatile')
# NOTE (Aug 2026): llama-3.3-70b-versatile is on Groq's deprecation list
# (shutdown 08/16/26); migrate to openai/gpt-oss-120b before it is cut off.
GROQ_VISION_MODEL = config('GROQ_VISION_MODEL', default='qwen/qwen3.6-27b')

# Rate limiting and upload sizes
RATE_LIMIT_AUTH = config('RATE_LIMIT_AUTH', default='5/m')
RATE_LIMIT_SUBMISSION = config('RATE_LIMIT_SUBMISSION', default='10/m')
RATE_LIMIT_SNAPSHOT = config('RATE_LIMIT_SNAPSHOT', default='30/m')
RATE_LIMIT_COMPLETION = config('RATE_LIMIT_COMPLETION', default='5/m')
MAX_AUDIO_MB = config('MAX_AUDIO_MB', default=10, cast=int)
MAX_IMAGE_MB = config('MAX_IMAGE_MB', default=2, cast=int)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5000',
    'http://127.0.0.1:5000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://8000-i09vg8t9d12an23lahp79-295b812f.sg1.manus.computer',
    'https://persona-app-sw4b.onrender.com',
]

# Render sets RENDER_HOSTNAME (or set it manually to your service's
# onrender.com / custom domain) so CSRF cookies work on the deployed site.
RENDER_HOSTNAME = os.environ.get('RENDER_HOSTNAME', '')
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS += [
        f'https://{RENDER_EXTERNAL_HOSTNAME}',
        f'http://{RENDER_EXTERNAL_HOSTNAME}',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PersonaFrontend',
    'UserAPI',
    'AnalysisAPI',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'PersonaBackend.middleware.RequestSizeLimitMiddleware',
    'PersonaBackend.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'PersonaBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'PersonaFrontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'UserAPI.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'PersonaBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Render sets DATABASE_URL automatically for Postgres; decouple it here so a
# single env var works out of the box while DB_NAME/DB_USER/... keep working.
import dj_database_url  # noqa: E402
DATABASE_URL = os.environ.get('DATABASE_URL', '')
DB_NAME = config('DB_NAME', default='')
if DATABASE_URL or DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': config('DB_USER', default=''),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
    if DATABASE_URL:
        DATABASES['default'] = dj_database_url.parse(
            DATABASE_URL, conn_max_age=600, ssl_require=True
        )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'PersonaFrontend' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Render serves static files straight from the container's dyno; WhiteNoise
# compresses/hashes them so collectstatic output is small and cacheable.
STORAGES = {
    'default': {
        # Pre-refactor the project relied on Django's implicit default media
        # file storage (FileSystemStorage). Explicitly restoring it here since
        # defining STORAGES without a 'default' key raises InvalidStorageError
        # on any model with an uploaded file (e.g. video uploads).
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session persistence for returning users
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# Note: SESSION_COOKIE_SECURE must be True in production (HTTPS). Dev uses False.
SESSION_COOKIE_SECURE = not DEBUG
# Note: In Replit dev, the preview URL hostname changes per container restart,
# so browser cookies from a previous session will not carry over. This is a
# Replit dev environment limitation. Sessions persist normally on the deployed
# .replit.app domain which is stable.

# Custom User Model
AUTH_USER_MODEL = 'UserAPI.CustomUser'

# Login/Logout URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Django-Q2 Configuration
Q_CLUSTER = {
        'name': 'persona_cluster',
        'workers': 4,
        'recycle': 500,
        'timeout': 300,
        'retry': 360,
        'catch_up': False,
        'orm': 'default'
    }

# Caching for Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
RATELIMIT_USE_CACHE = 'default'

# Security Headers (Part C)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# CSP (django-csp)
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://checkout.razorpay.com", "https://cdn.jsdelivr.net")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "data:")
CSP_IMG_SRC = ("'self'", "data:", "blob:")
CSP_CONNECT_SRC = ("'self'", "api.groq.com", "https://api.razorpay.com", "https://cdn.jsdelivr.net", "https://storage.googleapis.com")
CSP_MEDIA_SRC = ("'self'", "blob:", "data:")
CSP_FRAME_SRC = ("'self'", "https://razorpay.com", "https://checkout.razorpay.com")

# Email Backend for Sales Inquiries and Password Reset
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'noreply@persona.ai')

# ─── Subscription / Feature Gating ─────────────────────────────────────────
# Emails that bypass ALL subscription checks (project owner / admin).
# Set this via .env SUBSCRIPTION_OWNER_EMAILS (comma-separated).
SUBSCRIPTION_OWNER_EMAILS = config(
    'SUBSCRIPTION_OWNER_EMAILS',
    default='',
    cast=lambda v: [e.strip() for e in v.split(',') if e.strip()] if v else []
)

# ─── Razorpay Payment Config ────────────────────────────────────────────────
# Read from .env — NEVER hardcode secrets. .env is gitignored.
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_TEST_MODE = config('RAZORPAY_TEST_MODE', default='true')

# Plan pricing (amounts in paise: 1 INR = 100 paise)
PLAN_PRICING = {
    'monthly': {'amount': 49900, 'duration_days': 30, 'label': 'Monthly (1 month)'},
    'season_pass': {'amount': 99900, 'duration_days': 90, 'label': 'Season Pass (3 months)'},
    'annual': {'amount': 299900, 'duration_days': 365, 'label': 'Annual (12 months)'},
}
