# Generated by Django 5.2.7 on 2025-10-08 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_code', models.CharField(max_length=8, unique=True)),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='UserAPI.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('assessment_type', models.CharField(choices=[('individual', 'Individual Practice'), ('business', 'Business Assessment')], max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='assessments/videos/')),
                ('recording_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('assessment_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AnalysisAPI.assessmentlink')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('eye_contact_score', models.FloatField(blank=True, null=True)),
                ('gesture_score', models.FloatField(blank=True, null=True)),
                ('attire_appropriateness', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('attire_feedback', models.TextField(blank=True)),
                ('speech_clarity', models.FloatField(blank=True, null=True)),
                ('speech_pace', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='AnalysisAPI.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='UserAPI.businessuser')),
            ],
            options={
                'unique_together': {('business_user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('situational', 'Situational'), ('general', 'General')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='AnalysisAPI.jobrole')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentlink',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisAPI.jobrole'),
        ),
    ]
