# Generated by Django 5.2.7 on 2025-10-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentlink',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='AnalysisAPI.jobrole'),
        ),
    ]
