# Generated by Django 5.2.7 on 2025-10-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0002_alter_assessmentlink_job_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentlink',
            old_name='link_id',
            new_name='unique_link',
        ),
        migrations.RemoveField(
            model_name='assessmentlink',
            name='business_user',
        ),
        migrations.RemoveField(
            model_name='assessmentlink',
            name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='assessmentlink',
            name='candidate_name',
        ),
    ]
