# Generated by Django 5.2.7 on 2025-10-08 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0003_rename_link_id_assessmentlink_unique_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('hr', 'Human Resources'), ('consulting', 'Consulting'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='IndividualAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('selected_questions', models.JSONField(default=list, help_text='List of question IDs for this assessment')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(default=1800, help_text='Estimated duration in seconds')),
                ('fullscreen_violations', models.PositiveIntegerField(default=0)),
                ('warnings_given', models.PositiveIntegerField(default=0)),
                ('browser_focus_lost', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('body_language_score', models.FloatField(blank=True, null=True)),
                ('attire_score', models.FloatField(blank=True, null=True)),
                ('speaking_score', models.FloatField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_assessments', to=settings.AUTH_USER_MODEL)),
                ('platform_job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisAPI.platformjobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('body_language', 'Body Language'), ('attire', 'Attire')], max_length=20)),
                ('image_file', models.FileField(upload_to='assessments/snapshots/')),
                ('timestamp', models.DateTimeField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('analysis_data', models.JSONField(default=dict)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='AnalysisAPI.individualassessment')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('situational', 'Situational'), ('general', 'General')], default='general', max_length=50)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Mandatory questions are always asked')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('expected_duration', models.PositiveIntegerField(default=120, help_text='Expected answer duration in seconds')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='AnalysisAPI.platformjobtitle')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assessments/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='assessments/video/')),
                ('response_text', models.TextField(blank=True, help_text='Transcribed text from audio')),
                ('question_started_at', models.DateTimeField()),
                ('response_started_at', models.DateTimeField(blank=True, null=True)),
                ('response_ended_at', models.DateTimeField(blank=True, null=True)),
                ('response_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('time_to_start', models.PositiveIntegerField(blank=True, help_text='Time taken to start speaking in seconds', null=True)),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('formality_score', models.FloatField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed analysis results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='AnalysisAPI.individualassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnalysisAPI.platformquestion')),
            ],
        ),
    ]
