# Generated by Django 5.2.7 on 2025-10-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0004_platformjobtitle_individualassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAssessmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('body_language', 'Body Language'), ('attire', 'Attire')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('analysis_data', models.JSONField(default=dict)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='AnalysisAPI.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assessments/business/audio/')),
                ('response_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='AnalysisAPI.assessment')),
            ],
            options={
                'ordering': ['question_order'],
                'unique_together': {('assessment', 'question_order')},
            },
        ),
    ]
