# Generated by Django 6.0.6 on 2026-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0006_add_ideal_answer_points_to_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='improvement_roadmap',
            field=models.JSONField(blank=True, help_text='Structured improvement roadmap JSON from generate_improvement_roadmap()', null=True),
        ),
    ]
