# Generated by Django 6.0.6 on 2026-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0007_individualassessment_improvement_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='voice_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformjobtitle',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('hr', 'Human Resources'), ('consulting', 'Consulting'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('analytics', 'Analytics'), ('management', 'Management'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
