# Generated by Django 6.0.6 on 2026-07-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0008_individualassessment_voice_confidence_score_and_more'),
        ('UserAPI', '0003_institutionmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='institution_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='UserAPI.institutionmembership'),
        ),
    ]
