# Generated by Django 6.0.6 on 2026-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0009_individualassessment_institution_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_action_plan',
            field=models.JSONField(blank=True, help_text='Structured action plan with timeline', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_generated_at',
            field=models.DateTimeField(blank=True, help_text='When AI coaching was generated', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_recommended_topics',
            field=models.JSONField(blank=True, help_text='List of recommended practice topics', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', help_text='Status of AI coaching generation', max_length=20),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_strengths',
            field=models.JSONField(blank=True, help_text='List of strengths identified', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_summary',
            field=models.TextField(blank=True, help_text='Overall summary of performance', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='ai_coach_weaknesses',
            field=models.JSONField(blank=True, help_text='List of weaknesses identified', null=True),
        ),
    ]
