# Generated by Django 6.0.6 on 2026-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0010_individualassessment_ai_coach_action_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='adaptive_mode',
            field=models.BooleanField(default=True, help_text='Whether adaptive difficulty adjustment is enabled'),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='adaptive_path',
            field=models.JSONField(blank=True, default=list, help_text='List of adaptive decisions: [{question_order, previous_difficulty, performance_score, next_difficulty, reason}]'),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='current_difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Current difficulty tier for adaptive selection', max_length=20),
        ),
    ]
