# Generated by Django 6.0.6 on 2026-07-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0013_adaptive_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='pending_follow_up_reason',
            field=models.TextField(blank=True, help_text='Reason for generating the follow-up', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='pending_follow_up_text',
            field=models.TextField(blank=True, help_text='AI-generated follow-up question waiting to be asked', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='session_follow_up_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of follow-ups asked in this session'),
        ),
        migrations.CreateModel(
            name='FollowUpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_prompt', models.TextField(help_text='The AI-generated follow-up question text')),
                ('follow_up_reason', models.TextField(blank=True, help_text='Why this follow-up was triggered', null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assessments/follow_up_audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='assessments/follow_up_video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='AnalysisAPI.individualassessmentresponse')),
            ],
        ),
    ]
