# Generated by Django 6.0.6 on 2026-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0014_individualassessment_pending_follow_up_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='skill_gap_analysis',
            field=models.JSONField(blank=True, help_text='Structured skill gaps/strengths JSON from generate_skill_gap_analysis()', null=True),
        ),
    ]
