# Generated by Django 6.0.6 on 2026-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0022_coverletter_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
