# Generated by Django 6.0.6 on 2026-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0027_individualassessment_interview_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualassessment',
            name='interview_mode',
            field=models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('stress', 'Stress')], default='hr', help_text='Interview style/mode for this assessment', max_length=20),
        ),
    ]
