# Generated by Django 6.0.6 on 2026-07-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0029_alter_individualassessment_interview_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('interview_style_notes', models.TextField(help_text="Description of the company's interview culture and style used to guide AI question generation.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='target_company',
            field=models.ForeignKey(blank=True, help_text='Optional target company selected for tailored questions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AnalysisAPI.companyprofile'),
        ),
    ]
