# Generated by Django 6.0.6 on 2026-07-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0030_companyprofile_individualassessment_target_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='hints_used_per_question',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks number of hints requested per question order'),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='is_practice_mode',
            field=models.BooleanField(default=False, help_text='Practice mode with hints enabled, not scored for real.'),
        ),
    ]
