# Generated by Django 6.0.6 on 2026-07-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0031_individualassessment_hints_used_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='cv_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='CV analysis processing state', max_length=20),
        ),
    ]
