# Generated by Django 6.0.6 on 2026-07-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0032_assessmentresult_cv_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='cv_analysis_events',
            field=models.JSONField(blank=True, default=list, help_text='List of CV-event dicts logged during analysis: {"timestamp_sec": int, "type": "eye_contact_drop"|"posture_drop"|"distraction"}. Events are only recorded on good→bad state transitions, not every sampled second.'),
        ),
    ]
