# Generated by Django 6.0.6 on 2026-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0033_assessmentresult_cv_analysis_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='cv_analysis_events',
            field=models.JSONField(blank=True, default=list, help_text='List of CV-event dicts logged during analysis: {"response_id": int, "question_order": int, "timestamp_sec": int, "type": "eye_contact_drop"|"posture_drop"|"distraction"}. '),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='cv_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='CV analysis processing state', max_length=20),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='eye_contact_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='gesture_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='posture_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
