# Generated by Django 6.0.6 on 2026-07-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0035_resumereview_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of resume file bytes for deduplication', max_length=64, null=True),
        ),
    ]
