# Generated by Django 6.0.7 on 2026-07-31 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0036_coverletter_file_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, help_text='Optional target job role for sharper mentor advice', max_length=255, null=True)),
                ('timeline', models.CharField(blank=True, help_text="Optional job-search timeline (e.g. '3 months', 'immediately')", max_length=255, null=True)),
                ('concern', models.TextField(blank=True, help_text='Optional primary concern or question the candidate wants addressed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_intakes', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Career Intakes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
