# Generated by Django 6.0.7 on 2026-08-01 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0037_career_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('resume', 'Resume Screen'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('completed', 'Completed')], default='resume', max_length=20)),
                ('final_outcome', models.CharField(choices=[('in_progress', 'In Progress'), ('eliminated_at_resume', 'Eliminated at Resume Screen'), ('eliminated_at_assessment', 'Eliminated at Assessment'), ('eliminated_at_interview', 'Eliminated at Interview'), ('offer', 'OFFER')], default='in_progress', max_length=30)),
                ('stage_results', models.JSONField(blank=True, default=dict)),
                ('ai_feedback_summary', models.TextField(blank=True, null=True)),
                ('ai_feedback_cached_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_drive_assessment', to='AnalysisAPI.individualassessment')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_drive_interview', to='AnalysisAPI.individualassessment')),
                ('resume_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AnalysisAPI.resumereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AnalysisAPI_placementdrive',
                'ordering': ['-created_at'],
            },
        ),
    ]
