# Generated by Django 6.0.6 on 2026-08-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0038_placementdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessmentresponse',
            name='interviewer_persona_id',
            field=models.CharField(blank=True, help_text='ID of the persona who asked this question', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individualassessment',
            name='interview_mode',
            field=models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('managerial', 'Managerial'), ('stress', 'Stress'), ('rapid_fire', 'Rapid Fire'), ('panel', 'Panel Interview')], default='hr', help_text='Interview style/mode for this assessment', max_length=20),
        ),
        migrations.CreateModel(
            name='PanelSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.JSONField(default=list, help_text="List of persona IDs in the panel (e.g. ['friendly_encouraging', 'professional_stern'])")),
                ('aggregated_score', models.FloatField(blank=True, null=True)),
                ('ai_synthesis_summary', models.TextField(blank=True)),
                ('ai_synthesis_cached_at', models.DateTimeField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, help_text='Hash of source data to detect changes for AI summary', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_session', to='AnalysisAPI.individualassessment')),
            ],
        ),
        migrations.CreateModel(
            name='PanelPersonaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_scores', to='AnalysisAPI.panelsession')),
            ],
            options={
                'unique_together': {('panel_session', 'persona_id')},
            },
        ),
    ]
