# Generated by Django 6.0.6 on 2026-08-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0039_individualassessmentresponse_interviewer_persona_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='integrity_strike_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of flagged events (fullscreen exit, tab switch)'),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='is_high_risk',
            field=models.BooleanField(default=False, help_text='Marked as high-risk due to repeated integrity violations'),
        ),
        migrations.CreateModel(
            name='EnvironmentIntegrityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('fullscreen_exit', 'Fullscreen Exit'), ('tab_switch', 'Tab Switch/Window Blur'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('devtools_opened', 'DevTools Opened')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_events', to='AnalysisAPI.individualassessment')),
            ],
            options={
                'verbose_name': 'Environment Integrity Event',
                'verbose_name_plural': 'Environment Integrity Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
