# Generated by Django 6.0.6 on 2026-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0040_individualassessment_integrity_strike_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessmentresponse',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Manual Skip'), ('timeout', 'Time Limit Exceeded'), ('camera_mic_unavailable', 'Camera/Microphone Unavailable'), ('microphone_unavailable', 'Microphone Unavailable'), ('rapid_fire_timeout', 'Rapid Fire Timeout')], help_text='Reason why this question was skipped', max_length=50, null=True),
        ),
    ]
