# Generated by Django 6.0.6 on 2026-08-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0041_individualassessmentresponse_skip_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentintegrityevent',
            name='event_type',
            field=models.CharField(choices=[('fullscreen_exit', 'Fullscreen Exit'), ('tab_switch', 'Tab Switch/Window Blur'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('devtools_opened', 'DevTools Opened'), ('face_mismatch', 'Face Mismatch'), ('no_face_detected', 'No Face Detected'), ('multiple_faces_detected', 'Multiple Faces Detected')], max_length=30),
        ),
    ]
