# Generated by Django 6.0.6 on 2026-08-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0042_alter_environmentintegrityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the assessment session', null=True),
        ),
        migrations.AlterField(
            model_name='environmentintegrityevent',
            name='event_type',
            field=models.CharField(choices=[('fullscreen_exit', 'Fullscreen Exit'), ('tab_switch', 'Tab Switch/Window Blur'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('devtools_opened', 'DevTools Opened'), ('face_mismatch', 'Face Mismatch'), ('no_face_detected', 'No Face Detected'), ('multiple_faces_detected', 'Multiple Faces Detected'), ('large_paste_detected', 'Large Paste Detected'), ('suspicious_typing_pattern', 'Suspicious Typing Pattern'), ('multiple_ip_same_user', 'Multiple IP Same User'), ('shared_ip_multiple_users', 'Shared IP Multiple Users')], max_length=30),
        ),
    ]
