# Generated by Django 6.0.6 on 2026-08-07 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisAPI', '0043_individualassessment_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualassessment',
            name='integrity_review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('cleared', 'Cleared'), ('confirmed_cheating', 'Confirmed Cheating'), ('invalidated', 'Invalidated')], default='unreviewed', help_text='Review status for flagged integrity events', max_length=30),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='integrity_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this assessment was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='individualassessment',
            name='integrity_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
